# Postgresql Configuration (commented out)
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/order_management_system
#    username: postgres
#    password: postgres
#    initialization-mode: always
#    initialize: true

# H2 runtime database localhost Configuration
spring:
  datasource:
    url: jdbc:h2:mem:billing-service
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  flyway:
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always

# Note: This line was included in the properties file but seems out of place
# hibernate.dialect.PostgreSQLDialect
